[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

# SPA routing: React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
